apiVersion: apps/v1
kind: Deployment
metadata:
  name: person-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-api
  template:
    metadata:
      labels:
        app: person-api
    spec:
      containers:
        - name: person-api
          image: person-api:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            # ConfigMap
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: person-api-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              valueFrom:
                configMapKeyRef:
                  name: person-api-config
                  key: SPRING_JPA_HIBERNATE_DDL_AUTO

            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: person-api-config
                  key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT

            # Secrets
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: username

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
